name: terraform-lint

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint Terraform
        uses: actionshub/terraform-lint@${{ github.HEAD_REF }}
